---
kind: pipeline
type: docker
name: typesense-go-ci

clone:
  depth: 1

steps:
  - name: build
    image: golang:1.15-alpine
    commands:
      - go build ./...

trigger:
  branch:
    - master
  event:
    - push
    - pull_request
